export const seedCategories = [
  {
    name: 'Electronics',
    slug: 'electronics',
    description: 'Smartphones, audio, cameras, and wearable technology',
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=500',
    icon: 'Tv',
    level: 0,
    order: 1,
    isActive: true,
  },
  {
    name: 'Computers & Accessories',
    slug: 'computers-accessories',
    description: 'Laptops, desktops, monitors, computer parts and storage',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500',
    icon: 'Laptop',
    level: 0,
    order: 2,
    isActive: true,
  },
  {
    name: 'Fashion & Clothing',
    slug: 'fashion',
    description: 'Men, women, and kids fashion, footwear, and accessories',
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=500',
    icon: 'Shirt',
    level: 0,
    order: 3,
    isActive: true,
  },
  {
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    description: 'Cookware, appliances, furniture, and home decor',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=500',
    icon: 'Home',
    level: 0,
    order: 4,
    isActive: true,
  },
  {
    name: 'Books',
    slug: 'books',
    description: 'Fiction, non-fiction, academic, and audiobooks',
    image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=500',
    icon: 'BookOpen',
    level: 0,
    order: 5,
    isActive: true,
  },
  {
    name: 'Beauty & Personal Care',
    slug: 'beauty-personal-care',
    description: 'Skincare, haircare, makeup, and personal grooming',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=500',
    icon: 'Sparkles',
    level: 0,
    order: 6,
    isActive: true,
  },
  {
    name: 'Sports & Outdoors',
    slug: 'sports-outdoors',
    description: 'Fitness gear, sportswear, camping, and outdoor equipment',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500',
    icon: 'Dumbbell',
    level: 0,
    order: 7,
    isActive: true,
  },
  {
    name: 'Toys & Games',
    slug: 'toys-games',
    description: 'Action figures, puzzles, board games, and learning toys',
    image: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=500',
    icon: 'Gamepad2',
    level: 0,
    order: 8,
    isActive: true,
  },
];

export default seedCategories;
