export const generateProducts = (categoryMap, brandMap, sellerId) => {
  return [
    {
      title: 'Apple iPhone 15 (128 GB) - Black',
      slug: 'apple-iphone-15-128-gb-black',
      description: 'DYNAMIC ISLAND COMES TO IPHONE 15 — Dynamic Island bubbles up alerts and Live Activities — so you do not miss them while you are doing something else. You can see who is calling, track your next ride, check your flight status, and so much more.',
      bulletPoints: [
        'Dynamic Island bubbles up alerts and Live Activities',
        '48MP Main camera with 2x Telephoto for high-resolution photos',
        'Next-generation portraits with focus and depth control',
        'A16 Bionic chip powers computational photography and graphics-intensive games',
        'USB-C connectivity for convenient charging with Mac/iPad cables',
      ],
      brand: brandMap['Apple'],
      brandName: 'Apple',
      category: categoryMap['electronics'],
      seller: sellerId,
      price: { original: 79900, current: 71290, discount: 11, currency: 'INR' },
      stock: 45,
      sku: 'IPHONE15-BLK-128',
      images: [
        { url: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800', isPrimary: true, alt: 'iPhone 15 Black Front' },
        { url: 'https://images.unsplash.com/photo-1695048133021-998845705354?w=800', isPrimary: false, alt: 'iPhone 15 Black Back' },
      ],
      specifications: [
        { key: 'Display', value: '6.1-inch Super Retina XDR' },
        { key: 'Processor', value: 'A16 Bionic Chip' },
        { key: 'Camera', value: '48MP Main + 12MP Ultra Wide' },
        { key: 'Connector', value: 'USB-C' },
      ],
      ratings: { average: 4.6, count: 1840, distribution: { 1: 40, 2: 60, 3: 140, 4: 400, 5: 1200 } },
      isFeatured: true,
      isActive: true,
      isApproved: true,
      shipping: { isFreeShipping: true, shippingCost: 0, estimatedDays: 1, isPrimeEligible: true },
      tags: ['smartphone', 'iphone', 'apple', 'mobile', '5g'],
      totalSold: 890,
    },
    {
      title: 'Samsung Galaxy S24 Ultra 5G (Titanium Gray, 12GB, 256GB Storage)',
      slug: 'samsung-galaxy-s24-ultra-5g-titanium-gray',
      description: 'Meet Galaxy S24 Ultra, the ultimate form of Galaxy Ultra with a new titanium exterior and a 17.25cm (6.8") flat display. It is an absolute marvel of design. Galaxy AI is here.',
      bulletPoints: [
        'Galaxy AI is here: Circle to Search, Live Translate, and Note Assist',
        'Armor Titanium shield built right into the frame',
        'Built-in S Pen writes new chapters of productivity',
        '200MP Main Camera with AI processing for ultra-clarity',
        'Snapdragon 8 Gen 3 for Galaxy with ray-tracing graphics',
      ],
      brand: brandMap['Samsung'],
      brandName: 'Samsung',
      category: categoryMap['electronics'],
      seller: sellerId,
      price: { original: 134999, current: 129999, discount: 4, currency: 'INR' },
      stock: 30,
      sku: 'SGS24U-TGRY-256',
      images: [
        { url: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800', isPrimary: true, alt: 'Samsung S24 Ultra Front' },
      ],
      specifications: [
        { key: 'Display', value: '6.8-inch Dynamic AMOLED 2X, 120Hz' },
        { key: 'Processor', value: 'Snapdragon 8 Gen 3 for Galaxy' },
        { key: 'RAM', value: '12 GB' },
        { key: 'Storage', value: '256 GB' },
      ],
      ratings: { average: 4.7, count: 950, distribution: { 1: 20, 2: 30, 3: 50, 4: 200, 5: 650 } },
      isFeatured: true,
      isActive: true,
      isApproved: true,
      shipping: { isFreeShipping: true, shippingCost: 0, estimatedDays: 1, isPrimeEligible: true },
      tags: ['samsung', 'galaxy', 'smartphone', '5g', 'ai'],
      totalSold: 420,
    },
    {
      title: 'Sony WH-1000XM5 Wireless Noise Canceling Headphones - Black',
      slug: 'sony-wh-1000xm5-wireless-headphones-black',
      description: 'The WH-1000XM5 headphones rewrite the rules for distraction-free listening. Two processors control 8 microphones for unprecedented noise cancellation and exceptional call quality.',
      bulletPoints: [
        'Industry-leading noise cancellation with 2 processors and 8 microphones',
        'Magnificent sound engineered to perfection with High-Resolution Audio',
        'Crystal clear hands-free calling with 4 beamforming microphones',
        'Up to 30-hour battery life with quick charging (3 min for 3 hours playback)',
        'Ultra-comfortable lightweight design with soft fit leather',
      ],
      brand: brandMap['Sony'],
      brandName: 'Sony',
      category: categoryMap['electronics'],
      seller: sellerId,
      price: { original: 34990, current: 28990, discount: 17, currency: 'INR' },
      stock: 60,
      sku: 'SONY-WH1000XM5-BLK',
      images: [
        { url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800', isPrimary: true, alt: 'Sony XM5 Headphones' },
      ],
      specifications: [
        { key: 'Battery Life', value: 'Up to 30 hours' },
        { key: 'Noise Cancellation', value: 'Active Noise Cancelling (ANC)' },
        { key: 'Bluetooth', value: 'Version 5.2, LDAC supported' },
      ],
      ratings: { average: 4.8, count: 3200, distribution: { 1: 50, 2: 50, 3: 200, 4: 600, 5: 2300 } },
      isFeatured: true,
      isActive: true,
      isApproved: true,
      dealInfo: {
        isDeal: true,
        dealPrice: 26990,
        dealStart: new Date(Date.now() - 24 * 60 * 60 * 1000),
        dealEnd: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        dealType: 'lightning',
      },
      shipping: { isFreeShipping: true, shippingCost: 0, estimatedDays: 1, isPrimeEligible: true },
      tags: ['headphones', 'sony', 'anc', 'wireless', 'audio'],
      totalSold: 1250,
    },
    {
      title: 'Apple MacBook Air 13" with M2 chip (8GB RAM, 256GB SSD) - Space Gray',
      slug: 'apple-macbook-air-13-m2-space-gray',
      description: 'Redesigned around the next-generation M2 chip, MacBook Air is strikingly thin and brings exceptional speed and power efficiency inside its durable all-aluminum enclosure.',
      bulletPoints: [
        'Strikingly thin design – weighs only 1.24 kg (2.7 pounds)',
        'Supercharged by M2 with an 8-core CPU and up to 10-core GPU',
        'Up to 18 hours of all-day battery life',
        '13.6-inch Liquid Retina display with over 500 nits of brightness',
        '1080p FaceTime HD camera and three-mic array',
      ],
      brand: brandMap['Apple'],
      brandName: 'Apple',
      category: categoryMap['computers-accessories'],
      seller: sellerId,
      price: { original: 99900, current: 89990, discount: 10, currency: 'INR' },
      stock: 25,
      sku: 'MBA-M2-13-SG',
      images: [
        { url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800', isPrimary: true, alt: 'MacBook Air M2' },
      ],
      specifications: [
        { key: 'Processor', value: 'Apple M2 8-Core CPU' },
        { key: 'RAM', value: '8 GB Unified Memory' },
        { key: 'Storage', value: '256 GB SSD' },
        { key: 'Screen Size', value: '13.6 inches' },
      ],
      ratings: { average: 4.7, count: 2100, distribution: { 1: 30, 2: 40, 3: 130, 4: 500, 5: 1400 } },
      isFeatured: true,
      isActive: true,
      isApproved: true,
      shipping: { isFreeShipping: true, shippingCost: 0, estimatedDays: 2, isPrimeEligible: true },
      tags: ['macbook', 'apple', 'laptop', 'm2', 'computer'],
      totalSold: 670,
    },
    {
      title: 'Dell New G15 Gaming Laptop (Intel Core i5-13450HX / 16GB / 512GB SSD / RTX 3050)',
      slug: 'dell-g15-gaming-laptop-intel-i5-rtx-3050',
      description: 'Get your game on with the high-performance Dell G15 gaming laptop, featuring Alienware-inspired thermal cooling and 13th Gen Intel Core processors with NVIDIA GeForce RTX graphics.',
      bulletPoints: [
        '13th Gen Intel Core i5-13450HX processor (up to 4.60 GHz, 10 cores)',
        'NVIDIA GeForce RTX 3050 with 6GB GDDR6 dedicated graphics',
        '16GB DDR5 4800MHz RAM paired with 512GB PCIe NVMe SSD',
        '15.6-inch FHD 120Hz anti-glare display with 250 nits',
        'Game Shift key activates dynamic performance mode',
      ],
      brand: brandMap['Dell'],
      brandName: 'Dell',
      category: categoryMap['computers-accessories'],
      seller: sellerId,
      price: { original: 89990, current: 72990, discount: 19, currency: 'INR' },
      stock: 40,
      sku: 'DELL-G15-5530-GRY',
      images: [
        { url: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800', isPrimary: true, alt: 'Dell G15 Gaming Laptop' },
      ],
      specifications: [
        { key: 'Processor', value: 'Intel Core i5-13450HX' },
        { key: 'Graphics', value: 'NVIDIA RTX 3050 6GB' },
        { key: 'RAM', value: '16GB DDR5' },
        { key: 'Display', value: '15.6" 120Hz FHD' },
      ],
      ratings: { average: 4.3, count: 640, distribution: { 1: 30, 2: 40, 3: 70, 4: 200, 5: 300 } },
      isFeatured: false,
      isActive: true,
      isApproved: true,
      shipping: { isFreeShipping: true, shippingCost: 0, estimatedDays: 3, isPrimeEligible: true },
      tags: ['dell', 'laptop', 'gaming', 'rtx', 'computer'],
      totalSold: 310,
    },
    {
      title: 'boAt Rockerz 450 Bluetooth On Ear Headphones with Mic (Luscious Black)',
      slug: 'boat-rockerz-450-bluetooth-headphones-black',
      description: 'Tap into instant musical bliss with boAt Rockerz 450. Equipped with 40mm dynamic drivers, experience immersive HD sound with deep bass and up to 15 hours of playback time.',
      bulletPoints: [
        'Playback- Up to 15 hours of continuous playtime',
        '40mm dynamic drivers deliver rhythmic audio immersion',
        'Ergonomic design with padded ear cushions for all-day comfort',
        'Dual modes: Enjoy wireless Bluetooth or 3.5mm AUX wired connectivity',
        'Easy integrated controls with built-in mic for voice assistant',
      ],
      brand: brandMap['boAt'],
      brandName: 'boAt',
      category: categoryMap['electronics'],
      seller: sellerId,
      price: { original: 3990, current: 1499, discount: 62, currency: 'INR' },
      stock: 200,
      sku: 'BOAT-RCKZ450-BLK',
      images: [
        { url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800', isPrimary: true, alt: 'boAt Rockerz 450' },
      ],
      specifications: [
        { key: 'Driver Size', value: '40 mm' },
        { key: 'Playtime', value: '15 Hours' },
        { key: 'Bluetooth', value: 'v5.0' },
      ],
      ratings: { average: 4.1, count: 14500, distribution: { 1: 1000, 2: 1200, 3: 2300, 4: 4000, 5: 6000 } },
      isFeatured: true,
      isActive: true,
      isApproved: true,
      dealInfo: {
        isDeal: true,
        dealPrice: 1299,
        dealStart: new Date(Date.now() - 12 * 60 * 60 * 1000),
        dealEnd: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
        dealType: 'daily',
      },
      shipping: { isFreeShipping: true, shippingCost: 0, estimatedDays: 2, isPrimeEligible: true },
      tags: ['boat', 'headphones', 'audio', 'bluetooth', 'budget'],
      totalSold: 8900,
    },
    {
      title: 'Nike Air Max 270 Men\'s Running Shoes - Black/White',
      slug: 'nike-air-max-270-mens-running-shoes-black',
      description: 'Boasting Nike\'s biggest heel Air unit yet, the Nike Air Max 270 delivers visible air cushioning under every step. Inspired by iconic Air Max shoes from the early 90s.',
      bulletPoints: [
        'Large Max Air 270 heel unit delivers responsive cushioning',
        'Stretchy inner sleeve creates a snug, sock-like fit',
        'Breathable mesh upper with synthetic overlays for structure',
        'Dual-density foam midsole provides soft support',
        'Rubber outsole with durable traction pods',
      ],
      brand: brandMap['Nike'],
      brandName: 'Nike',
      category: categoryMap['fashion'],
      seller: sellerId,
      price: { original: 14995, current: 11995, discount: 20, currency: 'INR' },
      stock: 45,
      sku: 'NIKE-AM270-BLK-10',
      images: [
        { url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800', isPrimary: true, alt: 'Nike Air Max 270' },
      ],
      specifications: [
        { key: 'Shoe Type', value: 'Running & Lifestyle' },
        { key: 'Closure', value: 'Lace-Up' },
        { key: 'Sole Material', value: 'Rubber' },
      ],
      ratings: { average: 4.5, count: 1120, distribution: { 1: 30, 2: 40, 3: 150, 4: 300, 5: 600 } },
      isFeatured: true,
      isActive: true,
      isApproved: true,
      shipping: { isFreeShipping: true, shippingCost: 0, estimatedDays: 2, isPrimeEligible: true },
      tags: ['nike', 'shoes', 'fashion', 'sneakers', 'running'],
      totalSold: 540,
    },
    {
      title: 'Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones',
      slug: 'atomic-habits-james-clear-hardcover',
      description: 'No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear, one of the world\'s leading experts on habit formation, reveals practical strategies that teach you exactly how to form good habits and break bad ones.',
      bulletPoints: [
        'Over 15 Million Copies Sold Worldwide',
        'Instant #1 New York Times & Wall Street Journal Bestseller',
        'Learn how to make time for new habits and overcome lack of willpower',
        'Practical step-by-step strategies for personal and professional growth',
      ],
      category: categoryMap['books'],
      seller: sellerId,
      price: { original: 799, current: 540, discount: 32, currency: 'INR' },
      stock: 350,
      sku: 'BOOK-ATOMIC-HABITS-HC',
      images: [
        { url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800', isPrimary: true, alt: 'Atomic Habits Book Cover' },
      ],
      specifications: [
        { key: 'Author', value: 'James Clear' },
        { key: 'Publisher', value: 'Random House Business' },
        { key: 'Language', value: 'English' },
        { key: 'Format', value: 'Hardcover, 320 pages' },
      ],
      ratings: { average: 4.9, count: 48000, distribution: { 1: 200, 2: 300, 3: 1500, 4: 8000, 5: 38000 } },
      isFeatured: true,
      isActive: true,
      isApproved: true,
      shipping: { isFreeShipping: true, shippingCost: 0, estimatedDays: 1, isPrimeEligible: true },
      tags: ['book', 'bestseller', 'self-help', 'productivity', 'habits'],
      totalSold: 22000,
    },
  ];
};

export default generateProducts;
